#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.3.2 effective-4.1.50 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef PRISMA_SWIFT_H
#define PRISMA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Prisma",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC6Prisma3API")
@interface API : NSObject
- (nonnull instancetype)initWithDebug:(BOOL)debug OBJC_DESIGNATED_INITIALIZER;
- (void)getWithUrl:(NSString * _Nonnull)url onSuccess:(void (^ _Nonnull)(NSArray<NSString *> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(NSInteger))onError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Translations;
@class Placeholder;
@class PlaceholderContent;
@protocol PrismaRedirectHandler;
@protocol PrismaDismissHandler;
@class Tracker;

SWIFT_CLASS("_TtC6Prisma6Client")
@interface Client : NSObject
@property (nonatomic) BOOL debug;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Client * _Nullable shared;)
+ (Client * _Nullable)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Client * _Nullable)value;
+ (void)loadWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto;
- (nonnull instancetype)initWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto OBJC_DESIGNATED_INITIALIZER;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler retries:(NSInteger)retries;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler;
- (void)subscribeWithDeviceToken:(NSString * _Nonnull)deviceToken;
- (void)convertWithCampaignId:(NSString * _Nonnull)campaignId callback:(void (^ _Nonnull)(BOOL))callback;
- (NSString * _Nonnull)getBaseURL SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCustomerId SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomerIdWithCustomerId:(NSString * _Nonnull)customerId;
- (NSString * _Nonnull)getAppToken SWIFT_WARN_UNUSED_RESULT;
- (Tracker * _Nonnull)getTracker SWIFT_WARN_UNUSED_RESULT;
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIColor;
@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma18ColorableStackView")
@interface ColorableStackView : UIStackView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma6Column")
@interface Column : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma14FunnelStepView")
@interface FunnelStepView : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma15DataCaptureStep")
@interface DataCaptureStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma9DataInput")
@interface DataInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class FunnelSyncContext;

SWIFT_CLASS("_TtC6Prisma6Funnel")
@interface Funnel : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<Funnel *> * _Nonnull s_activeFunnels;)
+ (NSSet<Funnel *> * _Nonnull)s_activeFunnels SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activeFunnels:(NSSet<Funnel *> * _Nonnull)value;
+ (void)closeActiveFunnels;
+ (BOOL)hasActiveFunnels SWIFT_WARN_UNUSED_RESULT;
- (void)closeCurrentView;
- (void)show;
- (Client * _Nonnull)getClient SWIFT_WARN_UNUSED_RESULT;
- (FunnelSyncContext * _Nonnull)getFunnelSyncContext SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)dismiss;
- (void)startWithSource:(NSString * _Nullable)source;
- (void)startWizardWithSource:(NSString * _Nullable)source;
- (BOOL)allowDismiss SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasSteps SWIFT_WARN_UNUSED_RESULT;
- (void)openFunnelLandingWithSource:(NSString * _Nullable)source;
- (NSString * _Nonnull)getFunnelLanding SWIFT_WARN_UNUSED_RESULT;
- (void)onFunnelViewClosed;
- (int64_t)getCampaign SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrackingToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrailId SWIFT_WARN_UNUSED_RESULT;
- (void)nextFunnelStep;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6Prisma17FunnelSyncContext")
@interface FunnelSyncContext : NSObject
@property (nonatomic, copy) NSString * _Nonnull viewName;
@property (nonatomic, copy) NSArray<Placeholder *> * _Nonnull placeholders;
@property (nonatomic, copy) BOOL (^ _Nullable onSynced)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull);
@property (nonatomic, strong) id <PrismaDismissHandler> _Nullable dismissHandler;
@property (nonatomic, strong) id <PrismaRedirectHandler> _Nullable redirectHandler;
- (nonnull instancetype)initWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIView;

SWIFT_PROTOCOL("_TtP6Prisma8UIBanner_")
@protocol UIBanner
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebViewConfiguration;
@class WKUserContentController;
@class WKScriptMessage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma14HtmlBannerView")
@interface HtmlBannerView : WKWebView <UIBanner, WKScriptMessageHandler>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setOnDismissWithFn:(void (^ _Nonnull)(void))fn;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dismissCalled SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHtmlContent:(NSString * _Nonnull)htmlContent width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getHTMLContent SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma15ImageBannerView")
@interface ImageBannerView : UIImageView <UIBanner>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (nonnull instancetype)initWithImageUrl:(NSString * _Nonnull)imageUrl width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6Prisma11MessageStep")
@interface MessageStep : FunnelStepView
@end

@class NSBundle;

SWIFT_CLASS("_TtC6Prisma10ModalPopup")
@interface ModalPopup : UIViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<ModalPopup *> * _Nonnull s_activePopups;)
+ (NSSet<ModalPopup *> * _Nonnull)s_activePopups SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activePopups:(NSSet<ModalPopup *> * _Nonnull)value;
+ (void)closeActivePopups;
+ (BOOL)hasActivePopups SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma8PageStep")
@interface PageStep : FunnelStepView
@end

@class WKNavigationAction;
@class WKFrameInfo;

SWIFT_CLASS("_TtC6Prisma11PageWebView")
@interface PageWebView : WKWebView <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma11Placeholder")
@interface Placeholder : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (void)clearContent;
- (void)setPrismaContextWithCtx:(NSDictionary<NSString *, NSString *> * _Nonnull)ctx;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getPrismaContext SWIFT_WARN_UNUSED_RESULT;
- (void)closePopup;
- (BOOL)hasOpenedPopup SWIFT_WARN_UNUSED_RESULT;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
@end


SWIFT_CLASS("_TtC6Prisma18PlaceholderContent")
@interface PlaceholderContent : NSObject
@property (nonatomic, copy) NSArray<id <UIBanner>> * _Nonnull banners;
- (BOOL)isPopup SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showClose SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)transitionTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma19PopupViewController")
@interface PopupViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC6Prisma16PrismaComboInput")
@interface PrismaComboInput : DataInput <UIPickerViewDataSource, UIPickerViewDelegate>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end

@class UIDatePicker;

SWIFT_CLASS("_TtC6Prisma15PrismaDateInput")
@interface PrismaDateInput : DataInput
- (void)datePickerValueChanged:(UIDatePicker * _Nonnull)sender;
@end


SWIFT_PROTOCOL("_TtP6Prisma20PrismaDismissHandler_")
@protocol PrismaDismissHandler
- (BOOL)onDismissedWithCampaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP6Prisma21PrismaRedirectHandler_")
@protocol PrismaRedirectHandler
- (BOOL)onRedirectWithUrl:(NSURL * _Nonnull)url campaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6Prisma12RedirectStep")
@interface RedirectStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma3Row")
@interface Row : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma7Tracker")
@interface Tracker : NSObject
- (nonnull instancetype)initWithPrisma:(Client * _Nonnull)prisma OBJC_DESIGNATED_INITIALIZER;
- (BOOL)initialized SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trace SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trail SWIFT_WARN_UNUSED_RESULT;
- (void)trackLocationWithUri:(NSString * _Nonnull)uri title:(NSString * _Nonnull)title;
- (void)reset;
- (API * _Nonnull)api SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma12Translations")
@interface Translations : NSObject
- (NSString * _Nullable)translateWithSection:(NSString * _Nonnull)section key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC6Prisma11WebViewStep")
@interface WebViewStep : FunnelStepView
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.3.2 effective-4.1.50 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef PRISMA_SWIFT_H
#define PRISMA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Prisma",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC6Prisma3API")
@interface API : NSObject
- (nonnull instancetype)initWithDebug:(BOOL)debug OBJC_DESIGNATED_INITIALIZER;
- (void)getWithUrl:(NSString * _Nonnull)url onSuccess:(void (^ _Nonnull)(NSArray<NSString *> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(NSInteger))onError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Translations;
@class Placeholder;
@class PlaceholderContent;
@protocol PrismaRedirectHandler;
@protocol PrismaDismissHandler;
@class Tracker;

SWIFT_CLASS("_TtC6Prisma6Client")
@interface Client : NSObject
@property (nonatomic) BOOL debug;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Client * _Nullable shared;)
+ (Client * _Nullable)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Client * _Nullable)value;
+ (void)loadWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto;
- (nonnull instancetype)initWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto OBJC_DESIGNATED_INITIALIZER;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler retries:(NSInteger)retries;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler;
- (void)subscribeWithDeviceToken:(NSString * _Nonnull)deviceToken;
- (void)convertWithCampaignId:(NSString * _Nonnull)campaignId callback:(void (^ _Nonnull)(BOOL))callback;
- (NSString * _Nonnull)getBaseURL SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCustomerId SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomerIdWithCustomerId:(NSString * _Nonnull)customerId;
- (NSString * _Nonnull)getAppToken SWIFT_WARN_UNUSED_RESULT;
- (Tracker * _Nonnull)getTracker SWIFT_WARN_UNUSED_RESULT;
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIColor;
@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma18ColorableStackView")
@interface ColorableStackView : UIStackView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma6Column")
@interface Column : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma14FunnelStepView")
@interface FunnelStepView : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma15DataCaptureStep")
@interface DataCaptureStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma9DataInput")
@interface DataInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class FunnelSyncContext;

SWIFT_CLASS("_TtC6Prisma6Funnel")
@interface Funnel : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<Funnel *> * _Nonnull s_activeFunnels;)
+ (NSSet<Funnel *> * _Nonnull)s_activeFunnels SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activeFunnels:(NSSet<Funnel *> * _Nonnull)value;
+ (void)closeActiveFunnels;
+ (BOOL)hasActiveFunnels SWIFT_WARN_UNUSED_RESULT;
- (void)closeCurrentView;
- (void)show;
- (Client * _Nonnull)getClient SWIFT_WARN_UNUSED_RESULT;
- (FunnelSyncContext * _Nonnull)getFunnelSyncContext SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)dismiss;
- (void)startWithSource:(NSString * _Nullable)source;
- (void)startWizardWithSource:(NSString * _Nullable)source;
- (BOOL)allowDismiss SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasSteps SWIFT_WARN_UNUSED_RESULT;
- (void)openFunnelLandingWithSource:(NSString * _Nullable)source;
- (NSString * _Nonnull)getFunnelLanding SWIFT_WARN_UNUSED_RESULT;
- (void)onFunnelViewClosed;
- (int64_t)getCampaign SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrackingToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrailId SWIFT_WARN_UNUSED_RESULT;
- (void)nextFunnelStep;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6Prisma17FunnelSyncContext")
@interface FunnelSyncContext : NSObject
@property (nonatomic, copy) NSString * _Nonnull viewName;
@property (nonatomic, copy) NSArray<Placeholder *> * _Nonnull placeholders;
@property (nonatomic, copy) BOOL (^ _Nullable onSynced)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull);
@property (nonatomic, strong) id <PrismaDismissHandler> _Nullable dismissHandler;
@property (nonatomic, strong) id <PrismaRedirectHandler> _Nullable redirectHandler;
- (nonnull instancetype)initWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIView;

SWIFT_PROTOCOL("_TtP6Prisma8UIBanner_")
@protocol UIBanner
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebViewConfiguration;
@class WKUserContentController;
@class WKScriptMessage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma14HtmlBannerView")
@interface HtmlBannerView : WKWebView <UIBanner, WKScriptMessageHandler>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setOnDismissWithFn:(void (^ _Nonnull)(void))fn;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dismissCalled SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHtmlContent:(NSString * _Nonnull)htmlContent width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getHTMLContent SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma15ImageBannerView")
@interface ImageBannerView : UIImageView <UIBanner>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (nonnull instancetype)initWithImageUrl:(NSString * _Nonnull)imageUrl width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6Prisma11MessageStep")
@interface MessageStep : FunnelStepView
@end

@class NSBundle;

SWIFT_CLASS("_TtC6Prisma10ModalPopup")
@interface ModalPopup : UIViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<ModalPopup *> * _Nonnull s_activePopups;)
+ (NSSet<ModalPopup *> * _Nonnull)s_activePopups SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activePopups:(NSSet<ModalPopup *> * _Nonnull)value;
+ (void)closeActivePopups;
+ (BOOL)hasActivePopups SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma8PageStep")
@interface PageStep : FunnelStepView
@end

@class WKNavigationAction;
@class WKFrameInfo;

SWIFT_CLASS("_TtC6Prisma11PageWebView")
@interface PageWebView : WKWebView <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma11Placeholder")
@interface Placeholder : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (void)clearContent;
- (void)setPrismaContextWithCtx:(NSDictionary<NSString *, NSString *> * _Nonnull)ctx;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getPrismaContext SWIFT_WARN_UNUSED_RESULT;
- (void)closePopup;
- (BOOL)hasOpenedPopup SWIFT_WARN_UNUSED_RESULT;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
@end


SWIFT_CLASS("_TtC6Prisma18PlaceholderContent")
@interface PlaceholderContent : NSObject
@property (nonatomic, copy) NSArray<id <UIBanner>> * _Nonnull banners;
- (BOOL)isPopup SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showClose SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)transitionTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma19PopupViewController")
@interface PopupViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC6Prisma16PrismaComboInput")
@interface PrismaComboInput : DataInput <UIPickerViewDataSource, UIPickerViewDelegate>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end

@class UIDatePicker;

SWIFT_CLASS("_TtC6Prisma15PrismaDateInput")
@interface PrismaDateInput : DataInput
- (void)datePickerValueChanged:(UIDatePicker * _Nonnull)sender;
@end


SWIFT_PROTOCOL("_TtP6Prisma20PrismaDismissHandler_")
@protocol PrismaDismissHandler
- (BOOL)onDismissedWithCampaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP6Prisma21PrismaRedirectHandler_")
@protocol PrismaRedirectHandler
- (BOOL)onRedirectWithUrl:(NSURL * _Nonnull)url campaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6Prisma12RedirectStep")
@interface RedirectStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma3Row")
@interface Row : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma7Tracker")
@interface Tracker : NSObject
- (nonnull instancetype)initWithPrisma:(Client * _Nonnull)prisma OBJC_DESIGNATED_INITIALIZER;
- (BOOL)initialized SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trace SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trail SWIFT_WARN_UNUSED_RESULT;
- (void)trackLocationWithUri:(NSString * _Nonnull)uri title:(NSString * _Nonnull)title;
- (void)reset;
- (API * _Nonnull)api SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma12Translations")
@interface Translations : NSObject
- (NSString * _Nullable)translateWithSection:(NSString * _Nonnull)section key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC6Prisma11WebViewStep")
@interface WebViewStep : FunnelStepView
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif

#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 effective-4.1.50 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef PRISMA_SWIFT_H
#define PRISMA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Prisma",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC6Prisma3API")
@interface API : NSObject
- (nonnull instancetype)initWithDebug:(BOOL)debug OBJC_DESIGNATED_INITIALIZER;
- (void)getWithUrl:(NSString * _Nonnull)url onSuccess:(void (^ _Nonnull)(NSArray<NSString *> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(NSInteger))onError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Translations;
@class Placeholder;
@class PlaceholderContent;
@protocol PrismaRedirectHandler;
@protocol PrismaDismissHandler;
@class Tracker;

SWIFT_CLASS("_TtC6Prisma6Client")
@interface Client : NSObject
@property (nonatomic) BOOL debug;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Client * _Nullable shared;)
+ (Client * _Nullable)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Client * _Nullable)value;
+ (void)loadWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto;
- (nonnull instancetype)initWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto OBJC_DESIGNATED_INITIALIZER;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler retries:(NSInteger)retries;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler;
- (void)subscribeWithDeviceToken:(NSString * _Nonnull)deviceToken;
- (void)convertWithCampaignId:(NSString * _Nonnull)campaignId callback:(void (^ _Nonnull)(BOOL))callback;
- (NSString * _Nonnull)getBaseURL SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCustomerId SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomerIdWithCustomerId:(NSString * _Nonnull)customerId;
- (NSString * _Nonnull)getAppToken SWIFT_WARN_UNUSED_RESULT;
- (Tracker * _Nonnull)getTracker SWIFT_WARN_UNUSED_RESULT;
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIColor;
@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma18ColorableStackView")
@interface ColorableStackView : UIStackView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma6Column")
@interface Column : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma14FunnelStepView")
@interface FunnelStepView : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma15DataCaptureStep")
@interface DataCaptureStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma9DataInput")
@interface DataInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class FunnelSyncContext;

SWIFT_CLASS("_TtC6Prisma6Funnel")
@interface Funnel : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<Funnel *> * _Nonnull s_activeFunnels;)
+ (NSSet<Funnel *> * _Nonnull)s_activeFunnels SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activeFunnels:(NSSet<Funnel *> * _Nonnull)value;
+ (void)closeActiveFunnels;
+ (BOOL)hasActiveFunnels SWIFT_WARN_UNUSED_RESULT;
- (void)closeCurrentView;
- (void)show;
- (Client * _Nonnull)getClient SWIFT_WARN_UNUSED_RESULT;
- (FunnelSyncContext * _Nonnull)getFunnelSyncContext SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)dismiss;
- (void)startWithSource:(NSString * _Nullable)source;
- (void)startWizardWithSource:(NSString * _Nullable)source;
- (BOOL)allowDismiss SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasSteps SWIFT_WARN_UNUSED_RESULT;
- (void)openFunnelLandingWithSource:(NSString * _Nullable)source;
- (NSString * _Nonnull)getFunnelLanding SWIFT_WARN_UNUSED_RESULT;
- (void)onFunnelViewClosed;
- (int64_t)getCampaign SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrackingToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrailId SWIFT_WARN_UNUSED_RESULT;
- (void)nextFunnelStep;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6Prisma17FunnelSyncContext")
@interface FunnelSyncContext : NSObject
@property (nonatomic, copy) NSString * _Nonnull viewName;
@property (nonatomic, copy) NSArray<Placeholder *> * _Nonnull placeholders;
@property (nonatomic, copy) BOOL (^ _Nullable onSynced)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull);
@property (nonatomic, strong) id <PrismaDismissHandler> _Nullable dismissHandler;
@property (nonatomic, strong) id <PrismaRedirectHandler> _Nullable redirectHandler;
- (nonnull instancetype)initWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIView;

SWIFT_PROTOCOL("_TtP6Prisma8UIBanner_")
@protocol UIBanner
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebViewConfiguration;
@class WKUserContentController;
@class WKScriptMessage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma14HtmlBannerView")
@interface HtmlBannerView : WKWebView <UIBanner, WKScriptMessageHandler>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setOnDismissWithFn:(void (^ _Nonnull)(void))fn;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dismissCalled SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHtmlContent:(NSString * _Nonnull)htmlContent width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getHTMLContent SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma15ImageBannerView")
@interface ImageBannerView : UIImageView <UIBanner>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (nonnull instancetype)initWithImageUrl:(NSString * _Nonnull)imageUrl width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6Prisma11MessageStep")
@interface MessageStep : FunnelStepView
@end

@class NSBundle;

SWIFT_CLASS("_TtC6Prisma10ModalPopup")
@interface ModalPopup : UIViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<ModalPopup *> * _Nonnull s_activePopups;)
+ (NSSet<ModalPopup *> * _Nonnull)s_activePopups SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activePopups:(NSSet<ModalPopup *> * _Nonnull)value;
+ (void)closeActivePopups;
+ (BOOL)hasActivePopups SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma8PageStep")
@interface PageStep : FunnelStepView
@end

@class WKNavigationAction;
@class WKFrameInfo;

SWIFT_CLASS("_TtC6Prisma11PageWebView")
@interface PageWebView : WKWebView <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma11Placeholder")
@interface Placeholder : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (void)clearContent;
- (void)setPrismaContextWithCtx:(NSDictionary<NSString *, NSString *> * _Nonnull)ctx;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getPrismaContext SWIFT_WARN_UNUSED_RESULT;
- (void)closePopup;
- (BOOL)hasOpenedPopup SWIFT_WARN_UNUSED_RESULT;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
@end


SWIFT_CLASS("_TtC6Prisma18PlaceholderContent")
@interface PlaceholderContent : NSObject
@property (nonatomic, copy) NSArray<id <UIBanner>> * _Nonnull banners;
- (BOOL)isPopup SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showClose SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)transitionTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma19PopupViewController")
@interface PopupViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC6Prisma16PrismaComboInput")
@interface PrismaComboInput : DataInput <UIPickerViewDataSource, UIPickerViewDelegate>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end

@class UIDatePicker;

SWIFT_CLASS("_TtC6Prisma15PrismaDateInput")
@interface PrismaDateInput : DataInput
- (void)datePickerValueChanged:(UIDatePicker * _Nonnull)sender;
@end


SWIFT_PROTOCOL("_TtP6Prisma20PrismaDismissHandler_")
@protocol PrismaDismissHandler
- (BOOL)onDismissedWithCampaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP6Prisma21PrismaRedirectHandler_")
@protocol PrismaRedirectHandler
- (BOOL)onRedirectWithUrl:(NSURL * _Nonnull)url campaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6Prisma12RedirectStep")
@interface RedirectStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma3Row")
@interface Row : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma7Tracker")
@interface Tracker : NSObject
- (nonnull instancetype)initWithPrisma:(Client * _Nonnull)prisma OBJC_DESIGNATED_INITIALIZER;
- (BOOL)initialized SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trace SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trail SWIFT_WARN_UNUSED_RESULT;
- (void)trackLocationWithUri:(NSString * _Nonnull)uri title:(NSString * _Nonnull)title;
- (void)reset;
- (API * _Nonnull)api SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma12Translations")
@interface Translations : NSObject
- (NSString * _Nullable)translateWithSection:(NSString * _Nonnull)section key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC6Prisma11WebViewStep")
@interface WebViewStep : FunnelStepView
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3.2 effective-4.1.50 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef PRISMA_SWIFT_H
#define PRISMA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Prisma",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC6Prisma3API")
@interface API : NSObject
- (nonnull instancetype)initWithDebug:(BOOL)debug OBJC_DESIGNATED_INITIALIZER;
- (void)getWithUrl:(NSString * _Nonnull)url onSuccess:(void (^ _Nonnull)(NSArray<NSString *> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(NSInteger))onError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Translations;
@class Placeholder;
@class PlaceholderContent;
@protocol PrismaRedirectHandler;
@protocol PrismaDismissHandler;
@class Tracker;

SWIFT_CLASS("_TtC6Prisma6Client")
@interface Client : NSObject
@property (nonatomic) BOOL debug;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Client * _Nullable shared;)
+ (Client * _Nullable)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Client * _Nullable)value;
+ (void)loadWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto;
- (nonnull instancetype)initWithServer:(NSString * _Nonnull)server port:(NSString * _Nonnull)port appToken:(NSString * _Nonnull)appToken customer:(NSString * _Nonnull)customer proto:(NSString * _Nonnull)proto OBJC_DESIGNATED_INITIALIZER;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler retries:(NSInteger)retries;
- (void)syncViewWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced onError:(void (^ _Nullable)(NSInteger))onError redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler;
- (void)subscribeWithDeviceToken:(NSString * _Nonnull)deviceToken;
- (void)convertWithCampaignId:(NSString * _Nonnull)campaignId callback:(void (^ _Nonnull)(BOOL))callback;
- (NSString * _Nonnull)getBaseURL SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCustomerId SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomerIdWithCustomerId:(NSString * _Nonnull)customerId;
- (NSString * _Nonnull)getAppToken SWIFT_WARN_UNUSED_RESULT;
- (Tracker * _Nonnull)getTracker SWIFT_WARN_UNUSED_RESULT;
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIColor;
@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma18ColorableStackView")
@interface ColorableStackView : UIStackView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma6Column")
@interface Column : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma14FunnelStepView")
@interface FunnelStepView : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma15DataCaptureStep")
@interface DataCaptureStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma9DataInput")
@interface DataInput : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class FunnelSyncContext;

SWIFT_CLASS("_TtC6Prisma6Funnel")
@interface Funnel : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<Funnel *> * _Nonnull s_activeFunnels;)
+ (NSSet<Funnel *> * _Nonnull)s_activeFunnels SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activeFunnels:(NSSet<Funnel *> * _Nonnull)value;
+ (void)closeActiveFunnels;
+ (BOOL)hasActiveFunnels SWIFT_WARN_UNUSED_RESULT;
- (void)closeCurrentView;
- (void)show;
- (Client * _Nonnull)getClient SWIFT_WARN_UNUSED_RESULT;
- (FunnelSyncContext * _Nonnull)getFunnelSyncContext SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)dismiss;
- (void)startWithSource:(NSString * _Nullable)source;
- (void)startWizardWithSource:(NSString * _Nullable)source;
- (BOOL)allowDismiss SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasSteps SWIFT_WARN_UNUSED_RESULT;
- (void)openFunnelLandingWithSource:(NSString * _Nullable)source;
- (NSString * _Nonnull)getFunnelLanding SWIFT_WARN_UNUSED_RESULT;
- (void)onFunnelViewClosed;
- (int64_t)getCampaign SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrackingToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTrailId SWIFT_WARN_UNUSED_RESULT;
- (void)nextFunnelStep;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6Prisma17FunnelSyncContext")
@interface FunnelSyncContext : NSObject
@property (nonatomic, copy) NSString * _Nonnull viewName;
@property (nonatomic, copy) NSArray<Placeholder *> * _Nonnull placeholders;
@property (nonatomic, copy) BOOL (^ _Nullable onSynced)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull);
@property (nonatomic, strong) id <PrismaDismissHandler> _Nullable dismissHandler;
@property (nonatomic, strong) id <PrismaRedirectHandler> _Nullable redirectHandler;
- (nonnull instancetype)initWithViewName:(NSString * _Nonnull)viewName placeholders:(NSArray<Placeholder *> * _Nonnull)placeholders onSynced:(BOOL (^ _Nullable)(NSDictionary<NSString *, PlaceholderContent *> * _Nonnull))onSynced redirectHandler:(id <PrismaRedirectHandler> _Nullable)redirectHandler dismissHandler:(id <PrismaDismissHandler> _Nullable)dismissHandler OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIView;

SWIFT_PROTOCOL("_TtP6Prisma8UIBanner_")
@protocol UIBanner
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebViewConfiguration;
@class WKUserContentController;
@class WKScriptMessage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma14HtmlBannerView")
@interface HtmlBannerView : WKWebView <UIBanner, WKScriptMessageHandler>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (void)setOnDismissWithFn:(void (^ _Nonnull)(void))fn;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dismissCalled SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHtmlContent:(NSString * _Nonnull)htmlContent width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getHTMLContent SWIFT_WARN_UNUSED_RESULT;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma15ImageBannerView")
@interface ImageBannerView : UIImageView <UIBanner>
- (UIView * _Nonnull)getView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeight SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getWidth SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (Funnel * _Nonnull)getFunnel SWIFT_WARN_UNUSED_RESULT;
- (void)setTranslationsWithTranslations:(Translations * _Nonnull)translations;
- (Translations * _Nonnull)getTranslations SWIFT_WARN_UNUSED_RESULT;
- (void)setOnStartFunnelWithFn:(void (^ _Nonnull)(void))fn;
- (nonnull instancetype)initWithImageUrl:(NSString * _Nonnull)imageUrl width:(NSInteger)width height:(NSInteger)height funnel:(Funnel * _Nonnull)funnel category:(NSString * _Nonnull)category group:(NSString * _Nonnull)group OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6Prisma11MessageStep")
@interface MessageStep : FunnelStepView
@end

@class NSBundle;

SWIFT_CLASS("_TtC6Prisma10ModalPopup")
@interface ModalPopup : UIViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSSet<ModalPopup *> * _Nonnull s_activePopups;)
+ (NSSet<ModalPopup *> * _Nonnull)s_activePopups SWIFT_WARN_UNUSED_RESULT;
+ (void)setS_activePopups:(NSSet<ModalPopup *> * _Nonnull)value;
+ (void)closeActivePopups;
+ (BOOL)hasActivePopups SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma8PageStep")
@interface PageStep : FunnelStepView
@end

@class WKNavigationAction;
@class WKFrameInfo;

SWIFT_CLASS("_TtC6Prisma11PageWebView")
@interface PageWebView : WKWebView <WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma11Placeholder")
@interface Placeholder : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (void)clearContent;
- (void)setPrismaContextWithCtx:(NSDictionary<NSString *, NSString *> * _Nonnull)ctx;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getPrismaContext SWIFT_WARN_UNUSED_RESULT;
- (void)closePopup;
- (BOOL)hasOpenedPopup SWIFT_WARN_UNUSED_RESULT;
- (void)setContentWithContent:(PlaceholderContent * _Nonnull)content;
@end


SWIFT_CLASS("_TtC6Prisma18PlaceholderContent")
@interface PlaceholderContent : NSObject
@property (nonatomic, copy) NSArray<id <UIBanner>> * _Nonnull banners;
- (BOOL)isPopup SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showClose SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)transitionTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC6Prisma19PopupViewController")
@interface PopupViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC6Prisma16PrismaComboInput")
@interface PrismaComboInput : DataInput <UIPickerViewDataSource, UIPickerViewDelegate>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end

@class UIDatePicker;

SWIFT_CLASS("_TtC6Prisma15PrismaDateInput")
@interface PrismaDateInput : DataInput
- (void)datePickerValueChanged:(UIDatePicker * _Nonnull)sender;
@end


SWIFT_PROTOCOL("_TtP6Prisma20PrismaDismissHandler_")
@protocol PrismaDismissHandler
- (BOOL)onDismissedWithCampaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP6Prisma21PrismaRedirectHandler_")
@protocol PrismaRedirectHandler
- (BOOL)onRedirectWithUrl:(NSURL * _Nonnull)url campaignId:(int64_t)campaignId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6Prisma12RedirectStep")
@interface RedirectStep : FunnelStepView
@end


SWIFT_CLASS("_TtC6Prisma3Row")
@interface Row : ColorableStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Prisma7Tracker")
@interface Tracker : NSObject
- (nonnull instancetype)initWithPrisma:(Client * _Nonnull)prisma OBJC_DESIGNATED_INITIALIZER;
- (BOOL)initialized SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trace SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)trail SWIFT_WARN_UNUSED_RESULT;
- (void)trackLocationWithUri:(NSString * _Nonnull)uri title:(NSString * _Nonnull)title;
- (void)reset;
- (API * _Nonnull)api SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Prisma12Translations")
@interface Translations : NSObject
- (NSString * _Nullable)translateWithSection:(NSString * _Nonnull)section key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC6Prisma11WebViewStep")
@interface WebViewStep : FunnelStepView
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif

#endif
